name: lingua_ai
description: "An AI-supported language learning app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.5
  http: ^1.6.0
  audioplayers: ^6.6.0
  google_fonts: ^8.1.0
  flutter_tts: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/language-learning.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
