class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'welcome_title': 'Welcome to\nLinguaAI',
      'welcome_subtitle': 'Your personal AI language coach',
      'welcome_back': 'Welcome back',
      'welcome_guest': 'Welcome, Guest',
      'keep_learning': 'Keep learning',
      'today': 'today',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'no_account': 'Don\'t have an account?',
      'register': 'Register',
      'create_account': 'Create Account',
      'start_journey': 'Start Your Journey',
      'signup_ai': 'Sign up to start learning with AI',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'already_account': 'Already have an account?',
      'hello': 'Hello',
      'continue_learning': "Let's continue learning",
      'level': 'Level',
      'xp': 'XP',
      'streak': 'Streak',
      'completed': 'Completed',
      'practicing': 'Practicing',
      'days': 'days',
      'available_lessons': 'Available Lessons',
      'min': 'min',
      'profile': 'Profile',
      'learning_stats': 'Learning Stats',
      'lessons': 'Lessons',
      'weekly_activity': 'Weekly Activity',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'language_pref': 'Switch Language (EN/TR)',
      'interface_language': 'Interface Language',
      'target_language': 'Target Language',
      'sound_effects': 'Sound Effects',
      'privacy': 'Privacy & Security',
      'help': 'Help & Support',
      'logout': 'Log Out',
      'ai_coach': 'AI Coach',
      'start_practicing': 'Start practicing with AI Coach',
      'type_message': 'Type your message...',
      'translate_sentence': 'Select the correct answer',
      'check': 'Check',
      'next': 'Next',
      'finish': 'Finish',
      'lesson_completed': 'Lesson Completed!',
      'you_scored': 'You scored',
      'you_earned': 'You earned',
      'great_job': 'Great job keeping up your streak!',
      'continue': 'Continue',
      'home': 'Home',
      'error_loading': 'Error loading lesson',
      'no_questions': 'No questions available in this lesson',
      'Beginner': 'Beginner',
      'Elementary': 'Elementary',
      'Pre-Intermediate': 'Pre-Intermediate',
      'Intermediate': 'Intermediate',
      'Upper-Intermediate': 'Upper-Intermediate',
      'Advanced': 'Advanced',
      'reset_progress': 'Reset Progress (Test)',
      'reset_language': 'Reset Language (Test)',
      'continue_as_guest': 'Continue as Guest',
      'fields_empty_error': 'Please fill in all fields',
      'invalid_email_error': 'Please enter a valid email',
      'password_length_error': 'Password must be at least 4 characters',
      'password_match_error': 'Passwords do not match',
      'guest_user': 'Guest User',
      'writing_practice': 'Writing Practice',
      'suggest_topic': 'Suggest Topic',
      'your_topic': 'Your Topic',
      'write_answer': 'Write your answer',
      'check_writing': 'Check Writing',
      'corrected_version': 'Corrected Version',
      'feedback': 'Feedback',
      'mistakes': 'Mistakes',
      'grammar': 'Grammar',
      'vocabulary': 'Vocabulary',
      'clarity': 'Clarity',
      'too_short_error': 'Please write at least 2 sentences.',
      'empty_text_error': 'Writing cannot be empty.',
      'select_topic_error': 'Please select a topic first.',
      'start': 'Start',
      'flashcards': 'Flashcards',
      'cards_due': 'cards due today',
      'all_caught_up': 'All Caught Up! 🎉',
      'no_cards_due': 'You have no cards due for review today. Keep learning to add more.',
      'start_review': 'Start Review',
      'quick_add_card': 'Quick Add Card',
      'english_word': 'English word',
      'turkish_translation': 'Turkish translation',
      'added': 'Added',
      'add': 'Add',
      'show_answer': 'Show Answer',
      'forgot': 'Forgot',
      'got_it': 'Got It',
      'how_well_knew': 'How well did you know this?',
      'back_to_dashboard': 'Back to Dashboard',
    },
    'tr': {
      'welcome_title': 'LinguaAI\'a\nHoş Geldiniz',
      'welcome_subtitle': 'Kişisel Yapay Zeka Dil Koçunuz',
      'welcome_back': 'Tekrar hoş geldin',
      'welcome_guest': 'Hoş geldin, Misafir',
      'keep_learning': 'Öğrenmeye devam et',
      'today': 'bugün',
      'email': 'E-posta',
      'password': 'Şifre',
      'forgot_password': 'Şifremi Unuttum?',
      'login': 'Giriş Yap',
      'no_account': 'Hesabınız yok mu?',
      'register': 'Kayıt Ol',
      'create_account': 'Hesap Oluştur',
      'start_journey': 'Yolculuğunuza Başlayın',
      'signup_ai': 'YZ ile öğrenmeye başlamak için kaydolun',
      'full_name': 'Ad Soyad',
      'confirm_password': 'Şifreyi Onayla',
      'already_account': 'Zaten hesabınız var mı?',
      'hello': 'Merhaba',
      'continue_learning': "Öğrenmeye devam edelim",
      'level': 'Seviye',
      'xp': 'XP',
      'streak': 'Seri',
      'completed': 'Tamamlanan',
      'practicing': 'Pratik Yapılıyor',
      'days': 'gün',
      'available_lessons': 'Mevcut Dersler',
      'min': 'dk',
      'profile': 'Profil',
      'learning_stats': 'Öğrenme İstatistikleri',
      'lessons': 'Dersler',
      'weekly_activity': 'Haftalık Aktivite',
      'settings': 'Ayarlar',
      'notifications': 'Bildirimler',
      'language_pref': 'Dili Değiştir (EN/TR)',
      'interface_language': 'Arayüz Dili',
      'target_language': 'Hedef Dil',
      'sound_effects': 'Ses Efektleri',
      'privacy': 'Gizlilik ve Güvenlik',
      'help': 'Yardım ve Destek',
      'logout': 'Çıkış Yap',
      'ai_coach': 'YZ Koç',
      'start_practicing': 'YZ Koç ile pratik yapmaya başla',
      'type_message': 'Mesajınızı yazın...',
      'translate_sentence': 'Doğru cevabı seçin',
      'check': 'Kontrol Et',
      'next': 'İleri',
      'finish': 'Bitir',
      'lesson_completed': 'Ders Tamamlandı!',
      'you_scored': 'Puanınız',
      'you_earned': 'Kazandığınız',
      'great_job': 'Serini koruduğun için harika iş çıkardın!',
      'continue': 'Devam Et',
      'home': 'Ana Sayfa',
      'error_loading': 'Ders yüklenirken hata oluştu',
      'no_questions': 'Bu derste soru bulunmuyor',
      'Beginner': 'Başlangıç',
      'Elementary': 'İlkokul Seviyesi',
      'Pre-Intermediate': 'Orta Öncesi',
      'Intermediate': 'Orta',
      'Upper-Intermediate': 'Üst Orta',
      'Advanced': 'İleri',
      'reset_progress': 'İlerlemeyi Sıfırla (Test)',
      'reset_language': 'Dili Sıfırla (Test)',
      'continue_as_guest': 'Misafir Olarak Devam Et',
      'fields_empty_error': 'Lütfen tüm alanları doldurun',
      'invalid_email_error': 'Lütfen geçerli bir e-posta girin',
      'password_length_error': 'Şifre en az 4 karakter olmalıdır',
      'password_match_error': 'Şifreler eşleşmiyor',
      'guest_user': 'Misafir Kullanıcı',
      'writing_practice': 'Yazma Pratiği',
      'suggest_topic': 'Konu Öner',
      'your_topic': 'Konun',
      'write_answer': 'Cevabını yaz',
      'check_writing': 'Yazımı Kontrol Et',
      'corrected_version': 'Düzeltilmiş Hali',
      'feedback': 'Geri Bildirim',
      'mistakes': 'Hatalar',
      'grammar': 'Dilbilgisi',
      'vocabulary': 'Kelime Bilgisi',
      'clarity': 'Anlaşılırlık',
      'too_short_error': 'Lütfen en az 2 cümle yazın.',
      'select_topic_error': 'Lütfen önce bir konu seçin.',
      'start': 'Başlat',
      'flashcards': 'Kelime Kartları',
      'cards_due': 'kart tekrarı var',
      'all_caught_up': 'Bugünlük Hepsi Bu! 🎉',
      'no_cards_due': 'Bugün tekrar edecek kartınız yok. Yeni kelimeler eklemek için dersleri tamamlayın.',
      'start_review': 'Tekrara Başla',
      'quick_add_card': 'Hızlı Kart Ekle',
      'english_word': 'İngilizce kelime',
      'turkish_translation': 'Türkçe çeviri',
      'added': 'Eklendi',
      'add': 'Ekle',
      'show_answer': 'Yanıtı Göster',
      'forgot': 'Unuttum',
      'got_it': 'Biliyorum',
      'how_well_knew': 'Bu kelimeyi ne kadar iyi bildiniz?',
      'back_to_dashboard': 'Kontrol Paneline Dön',
    }
  };
}
