class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'welcome_title': 'Welcome to\nLinguaAI',
      'welcome_subtitle': 'Your personal AI language coach',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'no_account': 'Don\'t have an account?',
      'register': 'Register',
      'create_account': 'Create Account',
      'start_journey': 'Start Your Journey',
      'signup_ai': 'Sign up to start learning with AI',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'already_account': 'Already have an account?',
      'hello': 'Hello',
      'continue_learning': "Let's continue learning",
      'level': 'Level',
      'xp': 'XP',
      'streak': 'Streak',
      'days': 'days',
      'available_lessons': 'Available Lessons',
      'min': 'min',
      'profile': 'Profile',
      'learning_stats': 'Learning Stats',
      'lessons': 'Lessons',
      'weekly_activity': 'Weekly Activity',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'language_pref': 'Switch Language (EN/TR)',
      'privacy': 'Privacy & Security',
      'help': 'Help & Support',
      'logout': 'Log Out',
      'ai_coach': 'AI Coach',
      'type_message': 'Type your message...',
      'translate_sentence': 'Select the correct answer',
      'check': 'Check',
      'next': 'Next',
      'finish': 'Finish',
      'lesson_completed': 'Lesson Completed!',
      'you_scored': 'You scored',
      'you_earned': 'You earned',
      'great_job': 'Great job keeping up your streak!',
      'continue': 'Continue',
      'home': 'Home',
      'error_loading': 'Error loading lesson',
      'no_questions': 'No questions available in this lesson',
      'Beginner': 'Beginner',
      'Intermediate': 'Intermediate',
      'Advanced': 'Advanced',
      'reset_progress': 'Reset Progress (Test)',
      'reset_language': 'Reset Language (Test)',
      'continue_as_guest': 'Continue as Guest',
      'fields_empty_error': 'Please fill in all fields',
      'invalid_email_error': 'Please enter a valid email',
      'password_length_error': 'Password must be at least 4 characters',
      'password_match_error': 'Passwords do not match',
      'guest_user': 'Guest User',
    },
    'tr': {
      'welcome_title': 'LinguaAI\'a\nHoş Geldiniz',
      'welcome_subtitle': 'Kişisel Yapay Zeka Dil Koçunuz',
      'email': 'E-posta',
      'password': 'Şifre',
      'forgot_password': 'Şifremi Unuttum?',
      'login': 'Giriş Yap',
      'no_account': 'Hesabınız yok mu?',
      'register': 'Kayıt Ol',
      'create_account': 'Hesap Oluştur',
      'start_journey': 'Yolculuğunuza Başlayın',
      'signup_ai': 'YZ ile öğrenmeye başlamak için kaydolun',
      'full_name': 'Ad Soyad',
      'confirm_password': 'Şifreyi Onayla',
      'already_account': 'Zaten hesabınız var mı?',
      'hello': 'Merhaba',
      'continue_learning': "Öğrenmeye devam edelim",
      'level': 'Seviye',
      'xp': 'XP',
      'streak': 'Seri',
      'days': 'gün',
      'available_lessons': 'Mevcut Dersler',
      'min': 'dk',
      'profile': 'Profil',
      'learning_stats': 'Öğrenme İstatistikleri',
      'lessons': 'Dersler',
      'weekly_activity': 'Haftalık Aktivite',
      'settings': 'Ayarlar',
      'notifications': 'Bildirimler',
      'language_pref': 'Dili Değiştir (EN/TR)',
      'privacy': 'Gizlilik ve Güvenlik',
      'help': 'Yardım ve Destek',
      'logout': 'Çıkış Yap',
      'ai_coach': 'YZ Koç',
      'type_message': 'Mesajınızı yazın...',
      'translate_sentence': 'Doğru cevabı seçin',
      'check': 'Kontrol Et',
      'next': 'İleri',
      'finish': 'Bitir',
      'lesson_completed': 'Ders Tamamlandı!',
      'you_scored': 'Puanınız',
      'you_earned': 'Kazandığınız',
      'great_job': 'Serini koruduğun için harika iş çıkardın!',
      'continue': 'Devam Et',
      'home': 'Ana Sayfa',
      'error_loading': 'Ders yüklenirken hata oluştu',
      'no_questions': 'Bu derste soru bulunmuyor',
      'Beginner': 'Başlangıç',
      'Intermediate': 'Orta',
      'Advanced': 'İleri',
      'reset_progress': 'İlerlemeyi Sıfırla (Test)',
      'reset_language': 'Dili Sıfırla (Test)',
      'continue_as_guest': 'Misafir Olarak Devam Et',
      'fields_empty_error': 'Lütfen tüm alanları doldurun',
      'invalid_email_error': 'Lütfen geçerli bir e-posta girin',
      'password_length_error': 'Şifre en az 4 karakter olmalıdır',
      'password_match_error': 'Şifreler eşleşmiyor',
      'guest_user': 'Misafir Kullanıcı',
    }
  };
}
