class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'welcome_title': 'Welcome to\nLinguaAI',
      'welcome_subtitle': 'Your personal AI language coach',
      'welcome_back': 'Welcome back',
      'welcome_guest': 'Welcome, Guest',
      'keep_learning': 'Keep learning',
      'today': 'today',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'no_account': 'Don\'t have an account?',
      'register': 'Register',
      'create_account': 'Create Account',
      'start_journey': 'Start Your Journey',
      'signup_ai': 'Sign up to start learning with AI',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'already_account': 'Already have an account?',
      'hello': 'Hello',
      'continue_learning': "Let's continue learning",
      'level': 'Level',
      'xp': 'XP',
      'streak': 'Streak',
      'completed': 'Completed',
      'practicing': 'Practicing',
      'days': 'days',
      'available_lessons': 'Available Lessons',
      'min': 'min',
      'profile': 'Profile',
      'learning_stats': 'Learning Stats',
      'lessons': 'Lessons',
      'weekly_activity': 'Weekly Activity',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'language_pref': 'Switch Language (EN/TR)',
      'interface_language': 'Interface Language',
      'target_language': 'Target Language',
      'sound_effects': 'Sound Effects',
      'privacy': 'Privacy & Security',
      'help': 'Help & Support',
      'logout': 'Log Out',
      'ai_coach': 'AI Coach',
      'start_practicing': 'Start practicing with AI Coach',
      'type_message': 'Type your message...',
      'translate_sentence': 'Select the correct answer',
      'check': 'Check',
      'next': 'Next',
      'finish': 'Finish',
      'lesson_completed': 'Lesson Completed!',
      'you_scored': 'You scored',
      'you_earned': 'You earned',
      'great_job': 'Great job keeping up your streak!',
      'continue': 'Continue',
      'home': 'Home',
      'error_loading': 'Error loading lesson',
      'no_questions': 'No questions available in this lesson',
      'Beginner': 'Beginner',
      'Elementary': 'Elementary',
      'Pre-Intermediate': 'Pre-Intermediate',
      'Intermediate': 'Intermediate',
      'Upper-Intermediate': 'Upper-Intermediate',
      'Advanced': 'Advanced',
      'reset_progress': 'Reset Progress (Test)',
      'reset_language': 'Reset Language (Test)',
      'continue_as_guest': 'Continue as Guest',
      'fields_empty_error': 'Please fill in all fields',
      'invalid_email_error': 'Please enter a valid email',
      'password_length_error': 'Password must be at least 4 characters',
      'password_match_error': 'Passwords do not match',
      'guest_user': 'Guest User',
      'writing_practice': 'Writing Practice',
      'suggest_topic': 'Suggest Topic',
      'your_topic': 'Your Topic',
      'write_answer': 'Write your answer',
      'check_writing': 'Check Writing',
      'corrected_version': 'Corrected Version',
      'feedback': 'Feedback',
      'mistakes': 'Mistakes',
      'grammar': 'Grammar',
      'vocabulary': 'Vocabulary',
      'clarity': 'Clarity',
      'too_short_error': 'Please write at least 2 sentences.',
      'empty_text_error': 'Writing cannot be empty.',
      'select_topic_error': 'Please select a topic first.',
      'start': 'Start',
      'flashcards': 'Flashcards',
      'cards_due': 'cards due today',
      'all_caught_up': 'All Caught Up! 🎉',
      'no_cards_due': 'You have no cards due for review today. Keep learning to add more.',
      'start_review': 'Start Review',
      'quick_add_card': 'Quick Add Card',
      'english_word': 'English word',
      'turkish_translation': 'Turkish translation',
      'added': 'Added',
      'add': 'Add',
      'show_answer': 'Show Answer',
      'forgot': 'Forgot',
      'got_it': 'Got It',
      'how_well_knew': 'How well did you know this?',
      'back_to_dashboard': 'Back to Dashboard',
      'pronunciation_practice': 'Pronunciation Practice',
      'pronunciation_practice_desc': 'Improve your speaking with AI feedback',
      'recognized_text': 'Recognized Text',
      'pronunciation_score': 'Pronunciation Score',
      'record': 'Record',
      'stop': 'Stop',
      'listen': 'Listen',
      'community': 'Community',
      'community_desc': 'Share tips, experiences, and advice with other learners.',
      'what_did_you_learn': 'What did you learn today?',
      'share_tip': 'Share a learning tip or advice...',
      'post': 'Post',
      'posting': 'Posting...',
      'add_image': 'Add Image',
      'remove_image': 'Remove Image',
      'no_posts_yet': 'No community posts yet. Share the first learning tip!',
      'error_loading_posts': 'Could not load community posts. Tap to retry.',
      'learning': 'Learning',
      'delete_post_title': 'Delete post?',
      'delete_post_warning': 'This action cannot be undone.',
      'edit': 'Edit',
      'delete': 'Delete',
      'like': 'Like',
      'cancel': 'Cancel',
      'save': 'Save',
      'confirm_delete': 'Are you sure you want to delete this post?',
      'empty_post_error': 'Post text or image is required!',
      'choose_lesson': 'Choose a lesson',
      'choose_flashcard': 'Choose a flashcard',
      'enter_word_sentence': 'Enter word or sentence in {lang}...',
      'confirm_delete_card': 'Are you sure you want to permanently delete this card?',
      'post_shared_success': 'Post shared successfully!',
      'post_deleted_success': 'Post deleted successfully',
      'flashcard_added_success': 'Flashcard added successfully!',
      'flashcard_updated_success': 'Flashcard updated successfully!',
      'flashcard_deleted_success': 'Flashcard deleted successfully!',
      'failed_save_card': 'Failed to save card',
      'failed_delete_card': 'Failed to delete card',
      'failed_share_post': 'Failed to share post',
      'failed_delete_post': 'Failed to delete post',
      'lang_english': 'English',
      'lang_german': 'German',
      'lang_spanish': 'Spanish',
      'lang_french': 'French',
      'lang_arabic': 'Arabic',
      'just_now': 'Just now',
      'm_ago': '{num}m ago',
      'h_ago': '{num}h ago',
      'd_ago': '{num}d ago',
      'failed_pick_image': 'Failed to pick image',
      'failed_update_like': 'Failed to update like',
      'failed_update_post': 'Failed to update post',
      'coach_connection_error': 'Connection error: Cannot communicate with AI Coach.',
      'xp_earned_badge_plus': '+10 XP Earned!',
      'learning_language': 'Learning Language',
      'which_language_learn': 'Which language do you want to learn?',
      'start_beginner_lessons': 'Start with beginner lessons',
      'all_languages': 'All Languages',
      'dark_mode': 'Dark Mode',
      'total': 'total',
      'manual_input': 'Manual',
      'target_sentence': 'Target sentence',
      'translation_optional': 'Translation (optional)',
      'translation_optional_placeholder': 'e.g. Hello → Merhaba',
      'practice_phrase': 'Select a phrase',
      'select_flashcard_word': 'Select a flashcard word',
      'no_flashcards_available': 'No flashcards available. Add some from the Flashcards screen.',
      'delete_flashcard_title': 'Delete Flashcard',
      'offline_mode': 'Offline Mode',
      'offline_coach_desc': 'This feature requires an active internet connection. Please reconnect to continue practicing with AI.',
      'offline_writing_desc': 'This feature requires an active internet connection. Please reconnect to assess your writing with AI.',
      'offline_pronunciation_desc': 'This feature requires an active internet connection. Please reconnect to assess your pronunciation with AI.',
      'offline_community_desc': 'Offline Mode: Viewing Cached Feed. Reconnect to post comments, share tips, or like posts.',
      'offline_viewing_cached': 'Offline Mode: Viewing Cached Data',
    },
    'tr': {
      'welcome_title': 'LinguaAI\'a\nHoş Geldiniz',
      'welcome_subtitle': 'Kişisel Yapay Zeka Dil Koçunuz',
      'welcome_back': 'Tekrar hoş geldin',
      'welcome_guest': 'Hoş geldin, Misafir',
      'keep_learning': 'Öğrenmeye devam et',
      'today': 'bugün',
      'email': 'E-posta',
      'password': 'Şifre',
      'forgot_password': 'Şifremi Unuttum?',
      'login': 'Giriş Yap',
      'no_account': 'Hesabınız yok mu?',
      'register': 'Kayıt Ol',
      'create_account': 'Hesap Oluştur',
      'start_journey': 'Yolculuğunuza Başlayın',
      'signup_ai': 'YZ ile öğrenmeye başlamak için kaydolun',
      'full_name': 'Ad Soyad',
      'confirm_password': 'Şifreyi Onayla',
      'already_account': 'Zaten hesabınız var mı?',
      'hello': 'Merhaba',
      'continue_learning': "Öğrenmeye devam edelim",
      'level': 'Seviye',
      'xp': 'XP',
      'streak': 'Seri',
      'completed': 'Tamamlanan',
      'practicing': 'Pratik Yapılıyor',
      'days': 'gün',
      'available_lessons': 'Mevcut Dersler',
      'min': 'dk',
      'profile': 'Profil',
      'learning_stats': 'Öğrenme İstatistikleri',
      'lessons': 'Dersler',
      'weekly_activity': 'Haftalık Aktivite',
      'settings': 'Ayarlar',
      'notifications': 'Bildirimler',
      'language_pref': 'Dili Değiştir (EN/TR)',
      'interface_language': 'Arayüz Dili',
      'target_language': 'Hedef Dil',
      'sound_effects': 'Ses Efektleri',
      'privacy': 'Gizlilik ve Güvenlik',
      'help': 'Yardım ve Destek',
      'logout': 'Çıkış Yap',
      'ai_coach': 'YZ Koç',
      'start_practicing': 'YZ Koç ile pratik yapmaya başla',
      'type_message': 'Mesajınızı yazın...',
      'translate_sentence': 'Doğru cevabı seçin',
      'check': 'Kontrol Et',
      'next': 'İleri',
      'finish': 'Bitir',
      'lesson_completed': 'Ders Tamamlandı!',
      'you_scored': 'Puanınız',
      'you_earned': 'Kazandığınız',
      'great_job': 'Serini koruduğun için harika iş çıkardın!',
      'continue': 'Devam Et',
      'home': 'Ana Sayfa',
      'error_loading': 'Ders yüklenirken hata oluştu',
      'no_questions': 'Bu derste soru bulunmuyor',
      'Beginner': 'Başlangıç',
      'Elementary': 'İlkokul Seviyesi',
      'Pre-Intermediate': 'Orta Öncesi',
      'Intermediate': 'Orta',
      'Upper-Intermediate': 'Üst Orta',
      'Advanced': 'İleri',
      'reset_progress': 'İlerlemeyi Sıfırla (Test)',
      'reset_language': 'Dili Sıfırla (Test)',
      'continue_as_guest': 'Misafir Olarak Devam Et',
      'fields_empty_error': 'Lütfen tüm alanları doldurun',
      'invalid_email_error': 'Lütfen geçerli bir e-posta girin',
      'password_length_error': 'Şifre en az 4 karakter olmalıdır',
      'password_match_error': 'Şifreler eşleşmiyor',
      'guest_user': 'Misafir Kullanıcı',
      'writing_practice': 'Yazma Pratiği',
      'suggest_topic': 'Konu Öner',
      'your_topic': 'Konun',
      'write_answer': 'Cevabını yaz',
      'check_writing': 'Yazımı Kontrol Et',
      'corrected_version': 'Düzeltilmiş Hali',
      'feedback': 'Geri Bildirim',
      'mistakes': 'Hatalar',
      'grammar': 'Dilbilgisi',
      'vocabulary': 'Kelime Bilgisi',
      'clarity': 'Anlaşılırlık',
      'too_short_error': 'Lütfen en az 2 cümle yazın.',
      'empty_text_error': 'Yazı alanı boş olamaz.',
      'select_topic_error': 'Lütfen önce bir konu seçin.',
      'start': 'Başlat',
      'flashcards': 'Kelime Kartları',
      'cards_due': 'kart tekrarı var',
      'all_caught_up': 'Bugünlük Hepsi Bu! 🎉',
      'no_cards_due': 'Bugün tekrar edecek kartınız yok. Yeni kelimeler eklemek için dersleri tamamlayın.',
      'start_review': 'Tekrara Başla',
      'quick_add_card': 'Hızlı Kart Ekle',
      'english_word': 'İngilizce kelime',
      'turkish_translation': 'Türkçe çeviri',
      'added': 'Eklendi',
      'add': 'Ekle',
      'show_answer': 'Yanıtı Göster',
      'forgot': 'Unuttum',
      'got_it': 'Biliyorum',
      'how_well_knew': 'Bu kelimeyi ne kadar iyi bildiniz?',
      'back_to_dashboard': 'Kontrol Paneline Dön',
      'pronunciation_practice': 'Telaffuz Pratiği',
      'pronunciation_practice_desc': 'Konuşmanızı yapay zeka geri bildirimi ile geliştirin',
      'recognized_text': 'Algılanan Metin',
      'pronunciation_score': 'Telaffuz Puanı',
      'record': 'Kaydet',
      'stop': 'Durdur',
      'listen': 'Dinle',
      'community': 'Topluluk',
      'community_desc': 'Diğer öğrencilerle ipuçları ve çalışma tavsiyeleri paylaş.',
      'what_did_you_learn': 'Bugün ne öğrendin?',
      'share_tip': 'Bir öğrenme ipucu veya tavsiyesi paylaş...',
      'post': 'Paylaş',
      'posting': 'Paylaşılıyor...',
      'add_image': 'Görsel Ekle',
      'remove_image': 'Görseli Kaldır',
      'no_posts_yet': 'Henüz topluluk gönderisi yok. İlk öğrenme ipucunu sen paylaş!',
      'error_loading_posts': 'Topluluk gönderileri yüklenemedi. Yeniden denemek için dokunun.',
      'learning': 'Öğrenilen',
      'delete_post_title': 'Gönderi silinsin mi?',
      'delete_post_warning': 'Bu işlem geri alınamaz.',
      'edit': 'Düzenle',
      'delete': 'Sil',
      'like': 'Beğen',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'confirm_delete': 'Bu gönderiyi silmek istediğinizden emin misiniz?',
      'empty_post_error': 'Gönderi metni veya görsel gereklidir!',
      'choose_lesson': 'Bir ders seçin',
      'choose_flashcard': 'Bir kelime kartı seçin',
      'enter_word_sentence': '{lang} dilinde kelime veya cümle girin...',
      'confirm_delete_card': 'Bu kartı kalıcı olarak silmek istediğinizden emin misiniz?',
      'post_shared_success': 'Gönderi başarıyla paylaşıldı!',
      'post_deleted_success': 'Gönderi başarıyla silindi',
      'flashcard_added_success': 'Kelime kartı başarıyla eklendi!',
      'flashcard_updated_success': 'Kelime kartı başarıyla güncellendi!',
      'flashcard_deleted_success': 'Kelime kartı başarıyla silindi!',
      'failed_save_card': 'Kart kaydedilemedi',
      'failed_delete_card': 'Kart silinemedi',
      'failed_share_post': 'Gönderi paylaşılamadı',
      'failed_delete_post': 'Gönderi silinemedi',
      'lang_english': 'İngilizce',
      'lang_german': 'Almanca',
      'lang_spanish': 'İspanyolca',
      'lang_french': 'Fransızca',
      'lang_arabic': 'Arapça',
      'just_now': 'Az önce',
      'm_ago': '{num}dk önce',
      'h_ago': '{num}sa önce',
      'd_ago': '{num}g önce',
      'failed_pick_image': 'Görsel seçilemedi',
      'failed_update_like': 'Beğeni güncellenemedi',
      'failed_update_post': 'Gönderi güncellenemedi',
      'coach_connection_error': 'Bağlantı hatası: YZ Koç ile iletişim kurulamadı.',
      'xp_earned_badge_plus': '+10 XP Kazanıldı!',
      'learning_language': 'Öğrenmek İstediğiniz Dil',
      'which_language_learn': 'Hangi dili öğrenmek istiyorsunuz?',
      'start_beginner_lessons': 'Başlangıç dersleri ile başla',
      'all_languages': 'Tüm Diller',
      'dark_mode': 'Koyu Tema',
      'total': 'toplam',
      'manual_input': 'Manuel',
      'target_sentence': 'Hedef cümle',
      'translation_optional': 'Çeviri (isteğe bağlı)',
      'translation_optional_placeholder': 'ör. Hello → Merhaba',
      'practice_phrase': 'Bir cümle seçin',
      'select_flashcard_word': 'Kelime kartı seçin',
      'no_flashcards_available': 'Kelime kartı bulunamadı. Kelime Kartları ekranından ekleyin.',
      'delete_flashcard_title': 'Kelime Kartını Sil',
      'offline_mode': 'Çevrimdışı Mod',
      'offline_coach_desc': 'Bu özellik aktif bir internet bağlantısı gerektirir. YZ Koç ile pratik yapmaya devam etmek için lütfen bağlanın.',
      'offline_writing_desc': 'Bu özellik aktif bir internet bağlantısı gerektirir. Yazınızı YZ ile değerlendirmek için lütfen bağlanın.',
      'offline_pronunciation_desc': 'Bu özellik aktif bir internet bağlantısı gerektirir. Telaffuzunuzu YZ ile değerlendirmek için lütfen bağlanın.',
      'offline_community_desc': 'Çevrimdışı Mod: Önbelleğe Alınmış Gönderiler. Paylaşım yapmak veya beğenmek için internet bağlantısı gereklidir.',
      'offline_viewing_cached': 'Çevrimdışı Mod: Önbelleğe Alınmış Verileri Görüntüleme',
    }
  };
}
