import React, { createContext, useContext, useState } from 'react';
import type { InterfaceLanguage } from '../types/language';

interface LanguageContextType {
  language: InterfaceLanguage;
  setLanguage: (lang: InterfaceLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<InterfaceLanguage, Record<string, string>> = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    lessons: 'Lessons',
    writing_practice: 'Writing Practice',
    ai_coach: 'AI Coach',
    flashcards: 'Flashcards',
    pronunciation_practice: 'Pronunciation',
    community: 'Community',
    profile: 'Profile',
    settings: 'Settings',

    // Common
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    added: 'Added!',
    back: 'Back',
    next: 'Next',
    continue: 'Continue',
    finish: 'Finish',
    start: 'Start',
    loading: 'Loading...',
    retry: 'Try Again',
    close: 'Close',
    search: 'Search',
    submit: 'Submit',
    level: 'Level',
    logout: 'Logout',
    like: 'Like',
    guest: 'Guest',
    score: 'Score',
    see_all: 'See All',
    of: 'of',

    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    continue_as_guest: 'Continue as Guest',
    sign_in: 'Sign In',
    create_account: 'Create Account',
    full_name: 'Full Name',
    your_ai_tutor: 'Your AI-powered language tutor',
    please_wait: 'Please wait...',
    or: 'or',
    dont_have_account: "Don't have an account?",
    already_have_account: "Already have an account?",
    sign_up_action: "Sign up",
    sign_in_action: "Sign in",
    login_failed: "Login failed. Please try again.",
    registration_failed: "Registration failed. Please try again.",

    // Dashboard
    welcome_back: 'Welcome back',
    welcome_guest: 'Welcome, Guest',
    total_xp: 'Total XP',
    completed_lessons: 'Completed Lessons',
    current_streak: 'Current Streak',
    weekly_activity: 'Weekly Activity',
    progress_stats: 'Progress Stats',
    quick_actions: 'Quick Actions',
    start_learning_now: 'Start learning now!',
    keep_learning: 'Keep learning',
    today: 'today',
    learning: 'Learning',
    xp: 'XP',
    streak: 'Streak',
    days: 'days',
    completed: 'Completed',
    current_level: 'Current Level',
    next_level: 'Next Level',
    progress_to_next: 'Progress to Next Level',
    progress: 'Progress',
    xp_earned: 'XP Earned',
    day_streak: 'day streak',
    lessons_done: 'Lessons Done',
    next_up: 'NEXT UP',
    manage_study_cards: 'Manage & Study Cards',
    flashcards_deck: 'Flashcards Deck',
    flashcards_deck_desc: 'Build your custom vocabulary deck and study with spaced repetition.',
    target_language_label: 'Target Language',
    learning_path: 'learning path',
    quick_add_card: 'Quick Add Card',

    // Lessons
    curriculum: 'Curriculum',
    lessons_completed_of: 'lessons completed',
    no_lessons_available: 'No lessons available for',
    done_badge: 'done',
    available_lessons: 'Available Lessons',
    min: 'min',
    questions: 'questions',
    complete_previous_to_unlock: 'Complete previous level to unlock',
    beginner: 'Beginner',
    elementary: 'Elementary',
    pre_intermediate: 'Pre-Intermediate',
    intermediate: 'Intermediate',
    upper_intermediate: 'Upper-Intermediate',
    advanced: 'Advanced',
    back_to_lessons: 'Back to Lessons',
    locked: 'Locked',
    review: 'Review',
    xp_reward_label: 'XP Reward',
    no_lessons_title: 'No Lessons Found',
    check_back_later: 'Please check back later or choose another language.',

    // Lesson Quiz
    lesson_unavailable: 'Lesson Unavailable',
    no_questions_found: 'No questions found for this lesson.',
    question: 'Question',
    xp_points: 'XP Points',
    fill_blank: 'Fill in the blank',
    match_meaning: 'Match the meaning',
    translate_label: 'Translate',
    correct: 'Correct!',
    incorrect: 'Incorrect!',
    correct_answer: 'Correct:',
    see_results: 'See Results',
    xp_earned_label: 'XP Earned',
    excellent_result: 'Excellent! 🎉',
    good_job_result: 'Good job! 👍',
    keep_practicing: 'Keep practicing! 💪',
    lesson_no_questions: 'This lesson currently has no questions. Please try another one.',

    // Writing Practice
    topic: 'Topic',
    suggest_topic: 'Suggest Topic',
    check_writing: 'Check Writing',
    corrected_version: 'Corrected Version',
    mistakes: 'Mistakes',
    grammar: 'Grammar',
    vocabulary: 'Vocabulary',
    clarity: 'Clarity',
    feedback: 'Feedback',
    try_another: 'Try Another',
    write_at_least_20_chars: 'Write at least 20 characters',
    writing_subtitle: 'Write in {lang} and get instant AI feedback',
    your_writing: 'Your Writing',
    words: 'words',
    chars: 'chars',
    analyzing: 'Analyzing...',
    ai_feedback_label: 'AI Feedback',
    overall_assessment: 'Overall Assessment',
    topic_placeholder: 'Enter your writing topic or click suggest...',
    write_about_topic: 'Write about "{topic}" in {lang}... (aim for 50+ words)',
    write_about_your_topic: 'Write about your topic in {lang}... (aim for 50+ words)',

    // AI Coach
    start_conversation: 'Start a conversation...',
    type_message: 'Type a message',
    practicing: 'Practicing',
    practicing_lang: 'Practicing {lang}',
    clear_chat: 'Clear Chat',
    clear_chat_confirm: 'Are you sure you want to clear the chat history?',
    ai_coach_welcome: 'Hello! I am your AI Coach',
    ai_coach_welcome_desc: "I'm here to help you practice {lang} through conversation. Pick a topic or type a message!",
    something_wrong: 'Something went wrong. Please try again.',
    ai_powered_coach: 'AI-powered language coach',
    prompt_restaurant: "Let's practice ordering food at a restaurant",
    prompt_grammar: "Explain past tense rules in {lang}",
    prompt_introduce: "How do I introduce myself formally?",
    prompt_shopping: "Help me practice shopping phrases",

    // Flashcards
    flashcards_subtitle: 'Create your custom cards and learn them using Spaced Repetition (SM-2).',
    add_new_card: 'Add New Card',
    study_due: 'Study Due',
    no_cards_title: 'No flashcards yet',
    no_cards_desc: 'Add words you want to remember. They will show up here and prompt you for reviews.',
    add_first_card: 'Add Your First Card',
    due_now: 'DUE NOW',
    learning_badge: 'LEARNING',
    next_review: 'Next:',
    reviews: 'Reviews:',
    loading_vocab: 'Loading your vocabulary deck...',
    offline_data: 'Unable to sync with server. Using offline data.',
    tts_unsupported: 'Text-to-speech is not supported on this browser.',
    add_flashcard_modal: 'Add New Flashcard',
    edit_flashcard_modal: 'Edit Flashcard',
    english_word_label: 'English Word',
    turkish_translation_label: 'Turkish Translation',
    example_sentence_optional: 'Example Sentence (Optional)',
    note_optional: 'Note (Optional)',
    save_card: 'Save Card',
    great_job: 'Great Job!',
    finished_reviewing: 'You have finished reviewing all',
    cards_today: 'cards for today.',
    average_score: 'Average Score',
    back_to_list: 'Back to Flashcard List',
    exit_study: '← Exit Study',
    spaced_rep: 'Spaced Repetition Study Deck',
    translation_label: 'Translation',
    click_to_flip: 'Click card to flip',
    get_hint: 'Get a hint',
    how_well_knew_sm2: 'How well did you know this word? (SM-2)',
    delete_flashcard_title: 'Delete Flashcard?',
    delete_flashcard_warning: 'Are you sure you want to permanently delete this card from your deck? This action cannot be undone.',
    flashcard_created: 'Flashcard created successfully!',
    flashcard_updated: 'Flashcard updated successfully!',
    flashcard_deleted: 'Flashcard deleted successfully!',
    field_required_error: 'English Word and Turkish Translation are required.',
    failed_save_card: 'Failed to save flashcard.',
    failed_delete_card: 'Failed to delete flashcard.',
    example_label: 'Example',
    note_label: 'Note',
    forgot: 'Forgot',
    hard: 'Hard',
    okay: 'Okay',
    easy: 'Easy',
    very_easy: 'Very Easy',
    perfect: 'Perfect',
    shuffle_deck: 'Shuffle Deck',
    play_slideshow: 'Play Slideshow',
    pause_slideshow: 'Pause Slideshow',
    fullscreen_mode: 'Fullscreen Mode',
    starts_with: 'Starts with',
    no_hint_available: 'No hint available.',
    placeholder_target_word: 'e.g. apple',
    no_cards_desc_language: 'No flashcards for this language yet.',
    placeholder_translation: 'e.g. elma',
    placeholder_example: 'e.g. I eat an apple every day.',
    placeholder_note: 'e.g. irregular plural, spelling tip',

    // Pronunciation
    pronunciation_practice_desc: 'Improve your speaking with AI feedback',
    pronunciation_subtitle: 'Practice pronunciation, record your voice, and get instant feedback.',
    record: 'Record',
    stop: 'Stop',
    listen: 'Listen',
    recognized_text: 'Recognized Text',
    pronunciation_score: 'Pronunciation Score',
    manual_input: 'Manual Input',
    from_flashcards: 'From Flashcards',
    target_sentence: 'Word or sentence to practice',
    translation_optional: 'Translation (optional)',
    translation_optional_placeholder: 'Enter the native translation (Turkish)...',
    select_flashcard_word: 'Select Flashcard Word',
    no_flashcards_available: 'No custom flashcards available. Create some in the Flashcards section first!',
    practice_phrase: 'Practice Phrase',
    audio_preview: 'Audio Preview',
    analyzing_speech: 'Analyzing Speech...',
    submit_for_assessment: 'SUBMIT FOR ASSESSMENT',
    analyzing_speech_desc: 'Python Whisper model is transcribing and Gemini is evaluating feedback.',
    evaluation_failed: 'Evaluation Failed',
    waiting_for_speech: 'Waiting for recording',
    waiting_for_speech_desc: 'Select or enter a phrase, record your voice, and submit it for assessment.',
    assessment_result: 'Assessment Result',
    expected: 'Expected',
    transcribed: 'Transcribed',
    ai_coaching_feedback: 'AI Coaching Feedback',
    xp_earned_badge: 'Earned +10 Learning XP!',
    mic_not_supported: 'Audio recording is not supported in this browser.',
    mic_permission_denied: 'Microphone permission denied. Please allow microphone access in your browser settings.',
    failed_pronunciation: 'Failed to analyze pronunciation. Please ensure the backend and Whisper service are running.',
    click_record_tip: 'Click Record and start speaking...',

    // Community
    share_tip_desc: 'Share tips, lesson experiences, and study ideas with other learners.',
    what_did_you_learn: 'What did you learn today?',
    add_image: 'Add Image',
    remove_image: 'Remove Image',
    post_btn: 'Post',
    no_posts_yet: 'No community posts yet. Share the first learning tip!',
    could_not_load_posts: 'Could not load community posts. Please try again.',
    learning_lang: 'Learning',
    delete_post_title: 'Delete post?',
    delete_post_warning: 'This action cannot be undone.',
    confirm_delete: 'Are you sure you want to delete this post?',
    updating: 'Updating...',
    posting: 'Posting...',
    all_languages: 'All Languages',
    share_placeholder: 'Share a tip or something you learned...',
    loading_posts: 'Loading community posts...',
    posted_successfully: 'Posted successfully!',
    file_too_large: 'File size exceeds 5MB limit',
    failed_submit_post: 'Failed to submit post. Please try again.',
    failed_update_post: 'Failed to update post',
    failed_delete_post: 'Failed to delete post',
    try_again: 'Try Again',

    // Profile
    profile_settings_title: 'Profile & Settings',
    manage_account: 'Manage your account and learning preferences',
    learning_settings: 'Learning Settings',
    sound_effects: 'Sound Effects',
    sound_desc: 'Play sounds for correct/incorrect answers',
    save_settings: 'Save Settings',
    settings_saved: 'Saved!',
    danger_zone: 'Danger Zone',
    reset_language_progress: 'Reset Language Progress',
    reset_lang_desc: 'Clears all progress.',
    reset_progress_btn: 'Reset Progress',
    reset_confirm_msg: 'Are you sure? This cannot be undone. All your {lang} learning progress will be permanently deleted.',
    yes_reset_all: 'Yes, Reset Everything',
    reset_warning: 'Warning: This will reset your progress for the current language.',
    interface_language: 'Interface Language',
    target_language: 'Target Learning Language',

    // Scores & Results
    excellent: 'Excellent!',
    good_job: 'Good Job!',
    keep_trying: 'Keep Trying!',
    translate_sentence: 'Translate the following sentence:',
    sound_effects_label: 'Sound Effects',

    // Language Names
    lang_english: 'English',
    lang_german: 'German',
    lang_spanish: 'Spanish',
    lang_french: 'French',
    lang_arabic: 'Arabic',

    // Dashboard dynamic strings
    xp_to: 'XP to {level}',
    xp_away_from: '{xp} XP away from {level}!',
    streak_roll: "You're on a roll!",

    // Lessons page difficulty and categories
    difficulty_beginner: 'Beginner',
    difficulty_easy: 'Easy',
    difficulty_medium: 'Medium',
    difficulty_hard: 'Hard',
    questions_count: 'questions',
    lesson_desc_beginner: 'Build your foundation — greetings, basics, and core vocabulary',
    lesson_desc_elementary: 'Build core grammar and expand vocabulary',
    lesson_desc_pre_intermediate: 'Tackle complex structures and real-world scenarios',

    // Time Ago
    just_now: 'Just now',
    m_ago: '{num}m ago',
    h_ago: '{num}h ago',
    d_ago: '{num}d ago',

    // Theme tooltips
    theme_light: 'Switch to Light Mode',
    theme_dark: 'Switch to Dark Mode',
    level_label: 'Level',
    offline_banner_text: 'You are currently offline. Safe progress & flashcards will sync when you reconnect.',
    offline_only_title: 'Offline Mode',
    offline_only_desc: 'This feature requires an active internet connection. Please reconnect to continue using this tool.',
    offline_community_feed: 'Offline Mode: Viewing Cached Feed',
  },

  tr: {
    // Navigation
    dashboard: 'Panel',
    lessons: 'Dersler',
    writing_practice: 'Yazma Pratiği',
    ai_coach: 'Yapay Zeka Koçu',
    flashcards: 'Kelime Kartları',
    pronunciation_practice: 'Telaffuz',
    community: 'Topluluk',
    profile: 'Profil',
    settings: 'Ayarlar',

    // Common
    cancel: 'İptal',
    save: 'Kaydet',
    edit: 'Düzenle',
    delete: 'Sil',
    add: 'Ekle',
    added: 'Eklendi!',
    back: 'Geri',
    next: 'Sıradaki',
    continue: 'Devam Et',
    finish: 'Bitir',
    start: 'Başla',
    loading: 'Yükleniyor...',
    retry: 'Tekrar Dene',
    close: 'Kapat',
    search: 'Ara',
    submit: 'Gönder',
    level: 'Seviye',
    logout: 'Çıkış Yap',
    like: 'Beğen',
    guest: 'Misafir',
    score: 'Puan',
    see_all: 'Tümünü Gör',
    of: '/',
    guest_label: 'Misafir',

    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    name: 'Ad',
    continue_as_guest: 'Misafir Olarak Devam Et',
    sign_in: 'Giriş Yap',
    create_account: 'Hesap Oluştur',
    full_name: 'Ad Soyad',
    your_ai_tutor: 'Yapay Zeka destekli dil öğretmeniniz',
    please_wait: 'Lütfen bekleyin...',
    or: 'veya',
    dont_have_account: 'Hesabınız yok mu?',
    already_have_account: 'Zaten bir hesabınız var mı?',
    sign_up_action: 'Kaydol',
    sign_in_action: 'Giriş yap',
    login_failed: 'Giriş başarısız. Lütfen tekrar deneyin.',
    registration_failed: 'Kayıt başarısız. Lütfen tekrar deneyin.',

    // Dashboard
    welcome_back: 'Tekrar hoş geldin',
    welcome_guest: 'Hoş geldin, Misafir',
    total_xp: 'Toplam XP',
    completed_lessons: 'Tamamlanan Dersler',
    current_streak: 'Mevcut Seri',
    weekly_activity: 'Haftalık Aktivite',
    progress_stats: 'İlerleme İstatistikleri',
    quick_actions: 'Hızlı İşlemler',
    start_learning_now: 'Şimdi öğrenmeye başla!',
    keep_learning: 'Öğrenmeye devam et',
    today: 'bugün',
    learning: 'Öğrenilen Dil',
    xp: 'XP',
    streak: 'Seri',
    days: 'gün',
    completed: 'Tamamlandı',
    current_level: 'Mevcut Seviye',
    next_level: 'Sonraki Seviye',
    progress_to_next: 'Sonraki Seviyeye İlerleme',
    progress: 'İlerleme',
    xp_earned: 'Kazanılan XP',
    day_streak: 'günlük seri',
    lessons_done: 'Tamamlanan Dersler',
    next_up: 'SIRADA',
    manage_study_cards: 'Kartları Yönet ve Çalış',
    flashcards_deck: 'Kelime Kartı Destesi',
    flashcards_deck_desc: 'Özel kelime kartı destenizi oluşturun ve aralıklı tekrar ile çalışın.',
    target_language_label: 'Hedef Dil',
    learning_path: 'öğrenme yolu',
    quick_add_card: 'Hızlı Kart Ekle',

    // Lessons
    curriculum: 'Müfredat',
    lessons_completed_of: 'ders tamamlandı',
    no_lessons_available: 'için ders mevcut değil',
    done_badge: 'tamamlandı',
    available_lessons: 'Mevcut Dersler',
    min: 'dk',
    questions: 'soru',
    complete_previous_to_unlock: 'Önceki seviyeyi tamamla',
    beginner: 'Başlangıç',
    elementary: 'Temel Seviye',
    pre_intermediate: 'Ön-Orta Seviye',
    intermediate: 'Orta Seviye',
    upper_intermediate: 'İleri-Orta Seviye',
    advanced: 'İleri Seviye',
    back_to_lessons: 'Derslere Geri Dön',
    locked: 'Kilitli',
    review: 'Tekrar Et',
    xp_reward_label: 'XP Ödülü',
    no_lessons_title: 'Ders Bulunamadı',
    check_back_later: 'Lütfen daha sonra tekrar kontrol edin veya başka bir dil seçin.',

    // Lesson Quiz
    lesson_unavailable: 'Ders Mevcut Değil',
    no_questions_found: 'Bu ders için soru bulunamadı.',
    question: 'Soru',
    xp_points: 'XP Puanı',
    fill_blank: 'Boşluğu doldurun',
    match_meaning: 'Anlamı eşleştirin',
    translate_label: 'Çevirin',
    correct: 'Doğru!',
    incorrect: 'Yanlış!',
    correct_answer: 'Doğru Cevap:',
    see_results: 'Sonuçları Gör',
    xp_earned_label: 'Kazanılan XP',
    excellent_result: 'Mükemmel! 🎉',
    good_job_result: 'Aferin! 👍',
    keep_practicing: 'Pratik yapmaya devam et! 💪',
    lesson_no_questions: 'Bu derste şu an için soru bulunmamaktadır. Lütfen başka bir ders deneyin.',

    // Writing Practice
    topic: 'Konu',
    suggest_topic: 'Konu Öner',
    check_writing: 'Yazıyı Kontrol Et',
    corrected_version: 'Düzeltilmiş Versiyon',
    mistakes: 'Hatalar',
    grammar: 'Dil Bilgisi',
    vocabulary: 'Kelime Bilgisi',
    clarity: 'Açıklık',
    feedback: 'Geri Bildirim',
    try_another: 'Başka Bir Tane Dene',
    write_at_least_20_chars: 'En az 20 karakter yazın',
    writing_subtitle: '{lang} dilinde yaz ve anında YZ geri bildirimi al',
    your_writing: 'Yazın',
    words: 'kelime',
    chars: 'karakter',
    analyzing: 'Analiz ediliyor...',
    ai_feedback_label: 'YZ Geri Bildirimi',
    overall_assessment: 'Genel Değerlendirme',
    topic_placeholder: 'Yazı konunuzu girin veya öner\'e tıklayın...',
    write_about_topic: '"{topic}" hakkında {lang} dilinde yazın... (50+ kelime hedefleyin)',
    write_about_your_topic: 'Konunuz hakkında {lang} dilinde yazın... (50+ kelime hedefleyin)',

    // AI Coach
    start_conversation: 'Konuşmayı başlat...',
    type_message: 'Bir mesaj yazın',
    practicing: 'Pratik Yapılıyor',
    practicing_lang: '{lang} Pratik Yapılıyor',
    clear_chat: 'Sohbeti Temizle',
    clear_chat_confirm: 'Sohbet geçmişini silmek istediğinizden emin misiniz?',
    ai_coach_welcome: 'Merhaba! Ben Yapay Zeka Koçunuz',
    ai_coach_welcome_desc: 'Sohbet ederek {lang} pratiği yapmanıza yardımcı olmak için buradayım. Bir konu seçin veya mesaj yazın!',
    something_wrong: 'Bir şeyler yanlış gitti. Lütfen tekrar deneyin.',
    ai_powered_coach: 'YZ destekli dil koçu',
    prompt_restaurant: 'Bir restoranda yemek siparişi verme pratiği yapalım',
    prompt_grammar: '{lang} dilindeki geçmiş zaman kurallarını açıkla',
    prompt_introduce: 'Kendimi resmi olarak nasıl tanıtırım?',
    prompt_shopping: 'Alışveriş kalıpları pratiği yapmama yardım et',

    // Flashcards
    flashcards_subtitle: 'Özel kartlarınızı oluşturun ve Aralıklı Tekrar (SM-2) ile öğrenin.',
    add_new_card: 'Yeni Kart Ekle',
    study_due: 'Tekrar Et',
    no_cards_title: 'Henüz kart yok',
    no_cards_desc: 'Hatırlamak istediğiniz kelimeleri ekleyin. Buraya çıkacak ve tekrar yapmanızı isteyecek.',
    add_first_card: 'İlk Kartınızı Ekleyin',
    due_now: 'TEKRAR VAR',
    learning_badge: 'ÖĞRENİLİYOR',
    next_review: 'Sonraki:',
    reviews: 'Tekrar:',
    loading_vocab: 'Kelime kartlarınız yükleniyor...',
    offline_data: 'Sunucuyla bağlantı kurulamadı. Çevrimdışı veriler kullanılıyor.',
    tts_unsupported: 'Bu tarayıcıda metin-ses dönüşümü desteklenmiyor.',
    add_flashcard_modal: 'Yeni Kart Ekle',
    edit_flashcard_modal: 'Kartı Düzenle',
    english_word_label: 'İngilizce Kelime',
    turkish_translation_label: 'Türkçe Çeviri',
    example_sentence_optional: 'Örnek Cümle (İsteğe bağlı)',
    note_optional: 'Not (İsteğe bağlı)',
    save_card: 'Kartı Kaydet',
    great_job: 'Harika İş!',
    finished_reviewing: 'Bugün için tüm',
    cards_today: 'kartı gözden geçirdiniz.',
    average_score: 'Ortalama Puan',
    back_to_list: 'Kart Listesine Dön',
    exit_study: '← Çalışmadan Çık',
    spaced_rep: 'Aralıklı Tekrar Çalışma Destesi',
    translation_label: 'Çeviri',
    click_to_flip: 'Çevirmek için kartı tıklayın',
    get_hint: 'İpucu al',
    how_well_knew_sm2: 'Bu kelimeyi ne kadar iyi bildiniz? (SM-2)',
    delete_flashcard_title: 'Kart Silinsin mi?',
    delete_flashcard_warning: 'Bu kartı destenizden kalıcı olarak silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    flashcard_created: 'Kart başarıyla oluşturuldu!',
    flashcard_updated: 'Kart başarıyla güncellendi!',
    flashcard_deleted: 'Kart başarıyla silindi!',
    field_required_error: 'İngilizce kelime ve Türkçe çeviri gereklidir.',
    failed_save_card: 'Kart kaydedilemedi.',
    failed_delete_card: 'Kart silinemedi.',
    example_label: 'Örnek',
    note_label: 'Not',
    forgot: 'Unuttum',
    hard: 'Zor',
    okay: 'İdare Eder',
    easy: 'Kolay',
    very_easy: 'Çok Kolay',
    perfect: 'Mükemmel',
    shuffle_deck: 'Desteyi Karıştır',
    play_slideshow: 'Slayt Gösterisini Başlat',
    pause_slideshow: 'Slayt Gösterisini Duraklat',
    fullscreen_mode: 'Tam Ekran Modu',
    starts_with: 'Şununla başlıyor',
    no_hint_available: 'İpucu bulunmamaktadır.',
    placeholder_target_word: 'örn. apple',
    no_cards_desc_language: 'Bu dil için henüz kelime kartı yok.',
    placeholder_translation: 'örn. elma',
    placeholder_example: 'örn. I eat an apple every day.',
    placeholder_note: 'örn. düzensiz çoğul, yazım ipucu',

    // Pronunciation
    pronunciation_practice_desc: 'Konuşmanızı yapay zeka geri bildirimi ile geliştirin',
    pronunciation_subtitle: 'Telaffuz pratiği yapın, sesinizi kaydedin ve anında geri bildirim alın.',
    record: 'Kaydet',
    stop: 'Durdur',
    listen: 'Dinle',
    recognized_text: 'Algılanan Metin',
    pronunciation_score: 'Telaffuz Puanı',
    manual_input: 'Manuel Giriş',
    from_flashcards: 'Kelime Kartlarından',
    target_sentence: 'Pratik yapılacak kelime veya cümle',
    translation_optional: 'Çeviri (isteğe bağlı)',
    translation_optional_placeholder: 'Türkçe çevirisini girin...',
    select_flashcard_word: 'Kelime Kartı Seç',
    no_flashcards_available: 'Özel kelime kartı bulunamadı. Önce Kelime Kartları bölümünde kart ekleyin!',
    practice_phrase: 'Pratik Cümlesi',
    audio_preview: 'Ses Önizlemesi',
    analyzing_speech: 'Konuşma Analiz Ediliyor...',
    submit_for_assessment: 'DEĞERLENDİRMEYE GÖNDER',
    analyzing_speech_desc: 'Python Whisper modeli transkrip ediyor, Gemini geri bildirim değerlendiriyor.',
    evaluation_failed: 'Değerlendirme Başarısız',
    waiting_for_speech: 'Kayıt bekleniyor',
    waiting_for_speech_desc: 'Bir kelime veya cümle seçin/yazın, sesinizi kaydedin ve değerlendirme için gönderin.',
    assessment_result: 'Değerlendirme Sonucu',
    expected: 'Beklenen',
    transcribed: 'Transkrip',
    ai_coaching_feedback: 'YZ Koçluk Geri Bildirimi',
    xp_earned_badge: '+10 Öğrenme XP\'i Kazandınız!',
    mic_not_supported: 'Bu tarayıcıda ses kaydı desteklenmiyor.',
    mic_permission_denied: 'Mikrofon izni reddedildi. Lütfen tarayıcı ayarlarınızdan mikrofon erişimine izin verin.',
    failed_pronunciation: 'Telaffuz analizi başarısız. Lütfen arka uç ve Whisper servisinin çalıştığından emin olun.',
    click_record_tip: 'Kaydet\'e tıklayın ve konuşmaya başlayın...',

    // Community
    share_tip_desc: 'Diğer öğrencilerle ipuçları, ders deneyimleri ve çalışma fikirleri paylaş.',
    what_did_you_learn: 'Bugün ne öğrendin?',
    add_image: 'Görsel Ekle',
    remove_image: 'Görseli Kaldır',
    post_btn: 'Paylaş',
    no_posts_yet: 'Henüz topluluk gönderisi yok. İlk öğrenme ipucunu sen paylaş!',
    could_not_load_posts: 'Topluluk gönderileri yüklenemedi. Lütfen tekrar deneyin.',
    learning_lang: 'Öğrenilen',
    delete_post_title: 'Gönderi silinsin mi?',
    delete_post_warning: 'Bu işlem geri alınamaz.',
    confirm_delete: 'Bu gönderiyi silmek istediğinizden emin misiniz?',
    updating: 'Güncelleniyor...',
    posting: 'Paylaşılıyor...',
    all_languages: 'Tüm Diller',
    share_placeholder: 'Öğrendiğiniz bir şeyi veya ipucu paylaşın...',
    loading_posts: 'Topluluk gönderileri yükleniyor...',
    posted_successfully: 'Başarıyla paylaşıldı!',
    file_too_large: 'Dosya boyutu 5MB sınırını aşıyor',
    failed_submit_post: 'Gönderi paylaşılamadı. Lütfen tekrar deneyin.',
    failed_update_post: 'Gönderi güncellenemedi',
    failed_delete_post: 'Gönderi silinemedi',
    try_again: 'Tekrar Dene',

    // Profile
    profile_settings_title: 'Profil ve Ayarlar',
    manage_account: 'Hesabınızı ve öğrenme tercihlerinizi yönetin',
    learning_settings: 'Öğrenme Ayarları',
    sound_effects: 'Ses Efektleri',
    sound_desc: 'Doğru/Yanlış cevaplar için ses çal',
    save_settings: 'Ayarları Kaydet',
    settings_saved: 'Kaydedildi!',
    danger_zone: 'Tehlike Bölgesi',
    reset_language_progress: 'Dil İlerlemesini Sıfırla',
    reset_lang_desc: 'Tüm ilerlemeyi sıfırlar.',
    reset_progress_btn: 'İlerlemeyi Sıfırla',
    reset_confirm_msg: 'Emin misiniz? Bu geri alınamaz. {lang} dilindeki tüm öğrenme ilerlemeniz kalıcı olarak silinecek.',
    yes_reset_all: 'Evet, Her Şeyi Sıfırla',
    reset_warning: 'Uyarı: Bu işlem mevcut dil için ilerlemenizi sıfırlayacaktır.',
    interface_language: 'Arayüz Dili',
    target_language: 'Öğrenilen Dil',

    // Scores & Results
    excellent: 'Mükemmel!',
    good_job: 'Tebrikler!',
    keep_trying: 'Denemeye Devam Et!',
    translate_sentence: 'Aşağıdaki cümleyi çeviriniz:',
    sound_effects_label: 'Ses Efektleri',

    // Language Names
    lang_english: 'İngilizce',
    lang_german: 'Almanca',
    lang_spanish: 'İspanyolca',
    lang_french: 'Fransızca',
    lang_arabic: 'Arapça',

    // Dashboard dynamic strings
    xp_to: '{level} için XP',
    xp_away_from: '{level} için {xp} XP kaldı!',
    streak_roll: 'Harika gidiyorsun!',

    // Lessons page difficulty and categories
    difficulty_beginner: 'Başlangıç',
    difficulty_easy: 'Kolay',
    difficulty_medium: 'Orta',
    difficulty_hard: 'Zor',
    questions_count: 'soru',
    lesson_desc_beginner: 'Temelinizi oluşturun — selamlaşmalar, temel bilgiler ve temel kelimeler',
    lesson_desc_elementary: 'Temel dilbilgisi oluşturun ve kelime dağarcığınızı genişletin',
    lesson_desc_pre_intermediate: 'Karmaşık yapıları ve gerçek dünya senaryolarını ele alın',

    // Time Ago
    just_now: 'Az önce',
    m_ago: '{num}dk önce',
    h_ago: '{num}sa önce',
    d_ago: '{num}g önce',

    // Theme tooltips
    theme_light: 'Açık Temaya Geç',
    theme_dark: 'Koyu Temaya Geç',
    level_label: 'Seviye',
    offline_banner_text: 'Şu anda çevrimdışısınız. Güvenli ilerlemeler ve kelime kartları tekrar bağlandığınızda senkronize edilecektir.',
    offline_only_title: 'Çevrimdışı Mod',
    offline_only_desc: 'Bu özellik aktif bir internet bağlantısı gerektirir. Bu aracı kullanmaya devam etmek için lütfen tekrar bağlanın.',
    offline_community_feed: 'Çevrimdışı Mod: Önbelleğe Alınmış Akış Görüntüleniyor',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<InterfaceLanguage>(() => {
    return (localStorage.getItem('linguaai_interface_language') as InterfaceLanguage) || 'en';
  });

  const setLanguage = (lang: InterfaceLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('linguaai_interface_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
